#Regresja wielomianowa

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
url='https://raw.githubusercontent.com/girishkuniyal/Predict-housing-prices-in-Portland/master/ex1data2.txt'
df=pd.read_csv(url,header=None)

In [ ]:
df.head()

0  1       2
0  2104  3  399900
1  1600  3  329900
2  2400  3  369000
3  1416  2  232000
4  3000  4  539900

In [ ]:
df.columns=['Size','Bedrooms','Price']
df.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [ ]:
X=df[['Size']]
y=df['Price']

In [ ]:
X.values[:5]

array([[2104],
       [1600],
       [2400],
       [1416],
       [3000]])

In [ ]:
y.values[:5]

array([399900, 329900, 369000, 232000, 539900])

In [ ]:
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X)
X_poly[:5]

array([[1.00000000e+00, 2.10400000e+03, 4.42681600e+06, 9.31402086e+09],
       [1.00000000e+00, 1.60000000e+03, 2.56000000e+06, 4.09600000e+09],
       [1.00000000e+00, 2.40000000e+03, 5.76000000e+06, 1.38240000e+10],
       [1.00000000e+00, 1.41600000e+03, 2.00505600e+06, 2.83915930e+09],
       [1.00000000e+00, 3.00000000e+03, 9.00000000e+06, 2.70000000e+10]])

In [ ]:
model = LinearRegression()
model.fit(X_poly,y)

LinearRegression()

In [ ]:
model.intercept_

236407.0358523208

In [ ]:
model.coef_

array([ 0.00000000e+00, -1.07855433e+02,  1.06190390e-01, -1.38299983e-05])

In [ ]:
predict_data = np.array([[3200], [3720]])
predict_data

array([[3200],
       [3720]])

In [ ]:
predict_data_poly = poly.transform(predict_data)
predict_data_poly

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


array([[1.0000000e+00, 3.2000000e+03, 1.0240000e+07, 3.2768000e+10],
       [1.0000000e+00, 3.7200000e+03, 1.3838400e+07, 5.1478848e+10]])

In [ ]:
model.predict(predict_data_poly)

array([525477.86332531, 592737.54295217])

In [ ]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

x_range=np.linspace(X['Size'].min(),X['Size'].max(),50)
y_range=model.predict(poly.fit_transform(x_range.reshape(-1,1)))

fig=px.scatter(x=X['Size'],y=y,opacity=0.65)
fig.add_traces(go.Scatter(x=x_range,y=y_range,name='Polynomial Regression Fit'))
fig.show()

In [ ]:
#wracamy do zbioru danych z wypożyczeniami rowerów

url='https://raw.githubusercontent.com/PacktPublishing/Python-Machine-Learning-Cookbook/master/Chapter01/bike_day.csv'
df=pd.read_csv(url)
df.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [ ]:
#jako zmienną zależną wybieramy cnt, jako niezależną atemp

y = df['cnt']
X = df[['atemp']]

In [ ]:
#formatujemy zmienną atemp na dwa stopnie potęgi

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)
X_poly[:5]

array([[1.        , 0.363625  , 0.13222314],
       [1.        , 0.353739  , 0.12513128],
       [1.        , 0.189405  , 0.03587425],
       [1.        , 0.212122  , 0.04499574],
       [1.        , 0.22927   , 0.05256473]])

In [ ]:
#trenujemy model na podstawie rozszerzonego zbioru (atemp i jej potęgi)

model = LinearRegression()
model.fit(X_poly,y)

LinearRegression()

In [ ]:
model.intercept_

-2155.0968932330406

In [ ]:
model.coef_

array([     0.        ,  22767.32495365, -16460.45125404])

In [ ]:
#stworzymy predykcję ilości wypożyczonych rowerów na dzień, w którym znormalizowana temperatura równała się 0.8

predict_data = np.array([[0.8]])
predict_data

array([[0.8]])

In [ ]:
predict_data_poly = poly.transform(predict_data)
predict_data

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but PolynomialFeatures was fitted with feature names



array([[0.8]])

In [ ]:
model.predict(predict_data_poly)

array([5524.0742671])

In [ ]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

x_range=np.linspace(X['atemp'].min(),X['atemp'].max(),50)
y_range=model.predict(poly.fit_transform(x_range.reshape(-1,1)))

fig=px.scatter(x=X['atemp'],y=y,opacity=0.65)
fig.add_traces(go.Scatter(x=x_range,y=y_range,name='Polynomial Regression Fit'))
fig.show()